"""Redaction and sanitization for structured log events.

Belt-and-suspenders enforcement of the logging policy's prohibited-field list
(see ``docs/observability.md``): the policy says services must not pass these
values, and this processor guarantees they cannot be emitted even if one slips
through. It runs on every record — structlog-native and stdlib-bridged alike —
before the record reaches stdout or the export ring buffer.

Three defenses, applied to every field:

- **Key denylist**: a value whose key names a credential/PII field is replaced
  with ``[REDACTED]``, never rendered.
- **Value sanitization**: control characters (including newlines) are stripped
  from string values to prevent log injection into non-JSON sinks.
- **Truncation**: an overlong string is cut to a cap so a raw payload or
  document text cannot ride through disguised as a message.

Structural keys that legitimately carry long multi-line text generated by the
runtime (tracebacks) are exempt from sanitization and truncation so failure
diagnostics survive; they are never a place untrusted user input is written.
"""

from __future__ import annotations

import re
from typing import Any

from structlog.types import EventDict, WrappedLogger

REDACTED = "[REDACTED]"
MAX_VALUE_LENGTH = 500
_TRUNCATION_MARKER = "…[truncated]"

# Substrings that mark a key as carrying a credential or personal identifier.
# Matched case-insensitively as substrings so `api_key`, `openrouter_api_key`,
# and `X-Api-Key` all trip the same rule.
_DENY_SUBSTRINGS = (
    "password",
    "passwd",
    "secret",
    "token",
    "api_key",
    "apikey",
    "authorization",
    "auth_header",
    "cookie",
    "session_id",
    "sessionid",
    "email",
    "username",
    "jwt",
    "dsn",
    "connection_string",
    "conn_str",
    "credential",
    "private_key",
)

# Keys whose values are runtime-generated diagnostics (tracebacks) that must
# keep their newlines and full length. Never a sink for untrusted user input.
_STRUCTURAL_KEYS = frozenset({"exception", "stack", "stack_info"})

_CONTROL_CHARS = re.compile(r"[\x00-\x08\x0b\x0c\x0e-\x1f\x7f]")
_NEWLINES = re.compile(r"[\r\n]+")


def _key_is_sensitive(key: str) -> bool:
    """Whether a field key names a credential or personal identifier."""
    lowered = key.lower()
    return any(token in lowered for token in _DENY_SUBSTRINGS)


def _sanitize_str(value: str) -> str:
    """Strip control characters and cap the length of an untrusted string."""
    cleaned = _NEWLINES.sub(" ", value)
    cleaned = _CONTROL_CHARS.sub("", cleaned)
    if len(cleaned) > MAX_VALUE_LENGTH:
        cleaned = cleaned[:MAX_VALUE_LENGTH] + _TRUNCATION_MARKER
    return cleaned


def _redact_value(key: str, value: Any) -> Any:
    """Recursively redact/sanitize one field value, keyed for the denylist."""
    if _key_is_sensitive(key):
        return REDACTED
    if isinstance(value, str):
        if key in _STRUCTURAL_KEYS:
            return value
        return _sanitize_str(value)
    if isinstance(value, dict):
        return {str(k): _redact_value(str(k), v) for k, v in value.items()}
    if isinstance(value, (list, tuple)):
        return [_redact_value(key, item) for item in value]
    return value


def redact_processor(
    _logger: WrappedLogger, _method_name: str, event_dict: EventDict
) -> EventDict:
    """structlog processor: redact and sanitize every field of an event."""
    return {key: _redact_value(key, value) for key, value in event_dict.items()}
